# usnig phython statistics library

In [5]:
import statistics as s
careem_bills = [234,342, 128, 232, 234, 800, 78, 95, 195]
cb_mean = s.mean(careem_bills)
cb_median = s.median(careem_bills)
cb_variance =  s.variance(careem_bills)

In [20]:
[print(i, eval(i)) for i in ['cb_mean', 'cb_median', 'cb_variance']]

cb_mean 259.77777777777777
cb_median 232
cb_variance 47807.19444444444


[None, None, None]

# Usning base python

In [28]:
c_mean = sum(careem_bills)/len(careem_bills)
c_median = sorted(careem_bills)[len(careem_bills)//2]
c_variance = sum([(i-c_mean) ** 2 for i in careem_bills])/(len(careem_bills)-1)
[print(i, eval(i)) for i in ['c_mean', 'c_median', 'c_variance']]

c_mean 259.77777777777777
c_median 232
c_variance 47807.19444444443


[None, None, None]

# Testing

In [64]:
import numpy as np
a = np.array([c_mean, c_median, c_variance], dtype=int)
b = np.array([cb_mean, cb_median, cb_variance], dtype=int)
a

array([  259,   232, 47807])

In [65]:
b

array([  259,   232, 47807])

In [66]:
a == b 

array([ True,  True,  True], dtype=bool)